main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('all-news', views.all_news, name='all-news'),
    path('details/<int:id>', views.details, name='details'),
    path('all-categories', views.all_categories, name='all-categories'),
    path('category/<int:id>', views.category, name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

# Category model
class Category(models.Model):
    title = models.CharField(max_length=150)
    category_image = models.ImageField(upload_to='imgs/')

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Categories'


# News model
class News(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    details = models.TextField()
    image = models.ImageField(upload_to='imgs/')
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title


class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=150)
    comment = models.TextField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.comment

main/views.py
from django.shortcuts import render
from .models import News, Category


# Home page
def index(request):
    first_news = News.objects.first()
    four_news = News.objects.all()[1:5]
    three_categories = Category.objects.all()[0:3]
    all_categories = Category.objects.all()

    return render(request, 'index.html', {
        'first_news': first_news,
        'four_news': four_news,
        'three_categories': three_categories,
        'all_categories': all_categories,
    })


# all news
def all_news(request):
    all_news = News.objects.all()
    return render(request, 'all-news.html', {
        'all_news': all_news
    })


# details page(full news)
def details(request, id):
    news = News.objects.get(pk=id)
    category = Category.objects.get(id=news.category.id)
    related_news = News.objects.filter(category=category).exclude(id=id)
    return render(request, 'details.html', {
        'news': news,
        'related_news': related_news,
    })


# Show all categories
def all_categories(request):
    all_cats = Category.objects.all()
    return render(request, 'categories.html', {
        'all_cats': all_cats,
    })


# Show a category
def category(request, id):
    category = Category.objects.get(id=id)
    news = News.objects.filter(category=category)
    return render(request, 'category-news.html', {
        'all_news': news,
        'category': category,
    })

main/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">All News</h3>
    <!-- News Box -->
    {% for news in all_news %}
    <div class="card mb-4 shadow">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="media/{{news.image}}" class="card-img" alt="{{news.title}}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <p class="card-text">{{news.details}} <a href="details/{{news.id}}" class="btn btn-sm btn-primary">Read full story</a></p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{% block title %}Home Page{% endblock %}</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="{% static 'layout/styles/styles.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'layout/styles/layout.css' %}" type="text/css" />
<script type="text/javascript" src="{% static 'layout/scripts/jquery.min.js' %}"></script>
<!-- Homepage Specific -->
<script type="text/javascript" src="{% static 'layout/scripts/galleryviewthemes/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'layout/scripts/galleryviewthemes/jquery.timers.1.2.js' %}"></script>
<script type="text/javascript" src="{% static 'layout/scripts/galleryviewthemes/jquery.galleryview.2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'layout/scripts/galleryviewthemes/jquery.galleryview.setup.js' %}"></script>
<!-- / Homepage Specific -->
</head>
<body id="top">
<div class="wrapper col0">
  <div id="topline">
    <p>Tel: xxxxx xxxxxxxxxx | Mail: info@domain.com</p>
    <ul>
      <li><a href="#">Libero</a></li>
      <li><a href="#">Maecenas</a></li>
      <li><a href="#">Mauris</a></li>
      <li class="last"><a href="#">Suspendisse</a></li>
    </ul>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper">
  <div id="header">
    <div class="fl_left">
      <h1><a href="index.html"><strong>N</strong>ews <strong>M</strong>agazine</a></h1>
      <p>Free Website Template</p>
    </div>
    <div class="fl_right"><a href="#"><img src="{% static 'media/468x60.gif' %}" alt="" /></a></div>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper col2">
  <div id="topbar">
    <div id="topnav">
      <ul>
        <li class="active"><a href="{% url 'index' %}"">Home</a></li>
        <li><a href="#">Categories</a>
          <ul>
            {% for category in all_categories %}
            <li><a href="{{ category.id }}">{{ category.title }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li><a href="pages/style-demo.html">Style Demo</a></li>
        <li><a href="{% url 'all-news' %}">All News</a></li>
        <li class="last"><a href="{% url 'all-categories' %}">All Categories</a></li>
      </ul>
    </div>
    <div id="search">
      <form action="#" method="post">
        <fieldset>
          <legend>Site Search</legend>
          <input type="text" value="Search Our Website&hellip;"  onfocus="this.value=(this.value=='Search Our Website&hellip;')? '' : this.value ;" />
          <input type="submit" name="go" id="go" value="Search" />
        </fieldset>
      </form>
    </div>
    <br class="clear" />
  </div>
</div>


{% block content %}

{% endblock %}

<div class="wrapper">
    <div id="footer">
      <div class="footbox">
        <h2>Lacus interdum</h2>
        <ul>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li><a href="#">Praesent et eros</a></li>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li class="last"><a href="#">Praesent et eros</a></li>
        </ul>
      </div>
      <div class="footbox">
        <h2>Lacus interdum</h2>
        <ul>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li><a href="#">Praesent et eros</a></li>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li class="last"><a href="#">Praesent et eros</a></li>
        </ul>
      </div>
      <div class="footbox">
        <h2>Lacus interdum</h2>
        <ul>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li><a href="#">Praesent et eros</a></li>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li class="last"><a href="#">Praesent et eros</a></li>
        </ul>
      </div>
      <div class="footbox">
        <h2>Lacus interdum</h2>
        <ul>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li><a href="#">Praesent et eros</a></li>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li class="last"><a href="#">Praesent et eros</a></li>
        </ul>
      </div>
      <div class="footbox last">
        <h2>Lacus interdum</h2>
        <ul>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li><a href="#">Praesent et eros</a></li>
          <li><a href="#">Lorem ipsum dolor</a></li>
          <li><a href="#">Suspendisse in neque</a></li>
          <li class="last"><a href="#">Praesent et eros</a></li>
        </ul>
      </div>
      <br class="clear" />
    </div>
  </div>
  <!-- ####################################################################################################### -->
  <div class="wrapper">
    <div id="socialise">
      <ul>
        <li><a href="#"><img src="media/facebook.gif" alt="" /><span>Facebook</span></a></li>
        <li><a href="#"><img src="media/rss.gif" alt="" /><span>FeedBurner</span></a></li>
        <li class="last"><a href="#"><img src="media/twitter.gif" alt="" /><span>Twitter</span></a></li>
      </ul>
      <div id="newsletter">
        <h2>NewsLetter Sign Up !</h2>
        <p>Please enter your Email and Name to join.</p>
        <form action="#" method="post">
          <fieldset>
            <legend>Digital Newsletter</legend>
            <div class="fl_left">
              <input type="text" value="Enter name here&hellip;"  onfocus="this.value=(this.value=='Enter name here&hellip;')? '' : this.value ;" />
              <input type="text" value="Enter email address&hellip;"  onfocus="this.value=(this.value=='Enter email address&hellip;')? '' : this.value ;" />
            </div>
            <div class="fl_right">
              <input type="submit" name="newsletter_go" id="newsletter_go" value="&raquo;" />
            </div>
          </fieldset>
        </form>
        <p>To unsubsribe please <a href="#">click here &raquo;</a>.</p>
      </div>
      <br class="clear" />
    </div>
  </div>
  <!-- ####################################################################################################### -->
  <div class="wrapper col8">
    <div id="copyright">
      <p class="fl_left">Copyright &copy; 2014 - All Rights Reserved - <a href="#">Domain Name</a></p>
      <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
      <br class="clear" />
    </div>
  </div>
  </body>
  </html>

main/templates/categories.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">All Categories</h3>
    <div class="row">
        <!--Category box-->
        {% for cat in all_cats %}
        <div class="col-md-4">
            <div class="card mb-3 shadow">
                <img src="media/{{cat.category_image}}" class="card-img" alt="{{cat.title}}">
                <div class="card-body">
                    <h5 class="card-title">{{cat.title}}</h5>
                    <hr/>
                    <p class="card-text">Lorem ipsum</p>
                    <p class="card-text"><a href="/category/{{cat.id}}" class="btn btn-sm btn-primary">All News</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}


<!-- <main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">category 1</h3>
    <!--News box-->
<!--    <div class="card mb-4 shadow">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="" class="card-img" alt="">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Lorem ipsum</p>
                    <p class="card-text"><a href="" class="btn btn-sm btn-primary">Read full story</a></p>
                </div>
            </div>
        </div>
    </div>
</main> -->

main/templates/category-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
    <h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
    <div class="card mb-4 shadow">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="media/{{news.image}}" class="card-img" alt="{{news.title}}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <p class="card-text">{{news.details}} <a href="details/{{news.id}}" class="btn btn-sm btn-primary">Read full story</a></p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/details.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
    <!-- featured news-->
    <div class="row my-3">
        <!--left-->
        <div class="col-md-8">
            <div class="card mb-3">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <hr/>
                    <p class="card-text">{{news.details}}</p>
                </div>
                <div class="card-footer">
                    In <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
                </div>
            </div>
            <!--Comments-->
            <div class="card mb-4">
                <div class="card-header">Add comment</div>
                <div class="card-body">
                    <form method="post">
                        <div class="form-group row">
                            <label class="col-md-2">Name<span class="text-danger">*</span></label>
                            <div class="col-md-10">
                                <input type="text" name="name" required class="form-control" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2">Email<span class="text-danger">*</span></label>
                            <div class="col-md-10">
                                <input type="emailtext" name="email" required class="form-control" />
                            </div>
                            <div class="form-group row">
                                <label class="col-md-2">Comment<span class="text-danger">*</span></label>
                                <div class="col-md-10">
                                    <textarea class="form-control" name="message" required></textarea>
                                </div>
                            </div>
                            
                        </div>
                        <input type="submit" class="btn btn-primary" />
                    </form>
                </div>
            </div>
            <!--Previous comments-->
            <div class="card my-4">
                <h6 class="card-header">Comments</h6>
                <div class="card-body">
                    <blockquote class="blockquote text-right">
                        <p class="mb-0">Lorem ipsum sdvsdv caac xzcac Ccsc</p>
                        <footer class="blockquote-footer">Name <cite title="Source Title">Email</cite></footer>
                    </blockquote>
                    <hr/>
                </div>
            </div>
        </div>
        <!--Related news-->
        <div class="col-md-4">
            <h3 class="mb-3 border-bottom pb-1">From this Category</h3>
            <!--Category box-->
            {% for news in related_news %}
            <div class="card mb-3 shadow">
                <img src="/media/{{news.image}}" class="card-img-top" alt="new 1">
                <div class="card-body">
                    <h5 class="card-title">{{news.title}}</h5>
                    <hr/>
                    <p class="card-text">{{news.details}}<a href="/details/{{news.id}}" class="btn btn-sm btn-primary">Read full story</a></p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% block content %}
<!-- ####################################################################################################### -->
<div class="wrapper">
  <div class="container">
    <div class="content">
      <div id="featured_slide">
        <ul id="featurednews">
          <li><img src="/media/{{ first_news.image }}" alt="{{ first_news.title }}" />
            <div class="panel-overlay">
              <h2>{{ first_news.title }}</h2>
              <p>{{ first_news.details }}
                <a href="/detail/{{ first_news.id }}">Continue Reading &raquo;</a></p>
            </div>
          </li>
          {% for news in four_news %}
          <li><img src="media/{{ news.image }}" alt="{{ news.title }}" />
            <div class="panel-overlay">
              <h2>{{ news.title }}</h2>
              <p>{{ news.details }}
                <a href="/details/{{ news.id }}">Continue Reading &raquo;</a></p>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="column">
      <ul class="latestnews">
        <li><img src="media/100x100.gif" alt="" />
          <p><strong><a href="#">Indonectetus facilis leo.</a></strong> Nullamlacus dui ipsum cons eque loborttis non euis que morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque.</p>
        </li>
        <li><img src="media/100x100.gif" alt="" />
          <p><strong><a href="#">Indonectetus facilis leo.</a></strong> Nullamlacus dui ipsum cons eque loborttis non euis que morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque.</p>
        </li>
        <li class="last"><img src="media/100x100.gif" alt="" />
          <p><strong><a href="#">Indonectetus facilis leo.</a></strong> Nullamlacus dui ipsum cons eque loborttis non euis que morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque.</p>
        </li>
      </ul>
    </div>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper">
  <div id="adblock">
    <div class="fl_left"><a href="#"><img src="media/468x60.gif" alt="" /></a></div>
    <div class="fl_right"><a href="#"><img src="media/468x60.gif" alt="" /></a></div>
    <br class="clear" />
  </div>

  {% for category in three_categories %}
  <section class="py-5">
    
    
    <!-- <div class="container"> -->
      <div id="hpage_cats">
      <h2><a href="{{ category.id }}">{{ category.title }} &raquo;</a></h2>
      <div class="row gx-5">
        
        <!-- Column -->
        {% for news in category.news_set.all %}
        {% if forloop.counter < 4 %}
        <div class="col-md-3">
          
          <div class="card">
            <img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
            <div class="card-body">
              <h5 class="card-title">{{ news.title }}</h5>
              <h7 class="card-subtitle">By Olu Alo</h7>
              <p>{{ news.details }}<a href="/details/{{news.id}}">Continue Reading &raquo;</a></p>
              <!-- <h7 class="card-footer">By Olu Alo</h7> -->
            </div>
          </div>
          
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    
    <!-- </div> -->
  </section>
  {% endfor %}
    



  <div id="hpage_cats">
    {% for category in three_categories %}
    {% for news in category.news_set.all %}
      {% if forloop.counter < 4 %}
    <div class="fl_left">
      <h2><a href="#">{{category.title}} &raquo;</a></h2>
      <!-- <img src="media/{{news.image}}" alt="" /> -->
      <p><strong><a href="#">{{news.title}}</a></strong></p>
      <p>{{news.details}}<a href="http://www.os-templates.com/">OS Templates</a>. For more CSS templates visit <a href="http://www.os-templates.com/">Free Website Templates</a></p>
    </div>
    <div class="fl_right">
      <h2><a href="#">{{category.title}} &raquo;</a></h2>
      <!-- <img src="media/{{news.image}}" alt="{{news.title}}" /> -->
      <p><strong><a href="#">{{news.title}}</a></strong></p>
      <p>{{news.details}}<a href="http://www.os-templates.com/">OS Templates</a>. For more CSS templates visit <a href="http://www.os-templates.com/">Free Website Templates</a></p>
    </div>
    {% endif %}
    {% endfor %}
    <br class="clear" />
    {% endfor %}
  </div>


    
    <!-- <br class="clear" /> -->
    
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper">
  <div class="container">
    <div class="content">
      <div id="hpage_latest">
        <h2>Feugiatrutrum rhoncus semper</h2>
        <ul>
          <li><img src="media/190x130.gif" alt="" />
            <p>Nullamlacus dui ipsum conseqlo borttis non euisque morbipen a sdapibulum orna.</p>
            <p>Urnau ltrices quis curabitur pha sellent esque congue magnisve stib ulum quismodo nulla et.</p>
            <p class="readmore"><a href="#">Continue Reading &raquo;</a></p>
          </li>
          <li><img src="media/190x130.gif" alt="" />
            <p>Nullamlacus dui ipsum conseqlo borttis non euisque morbipen a sdapibulum orna.</p>
            <p>Urnau ltrices quis curabitur pha sellent esque congue magnisve stib ulum quismodo nulla et.</p>
            <p class="readmore"><a href="#">Continue Reading &raquo;</a></p>
          </li>
          <li class="last"><img src="media/190x130.gif" alt="" />
            <p>Nullamlacus dui ipsum conseqlo borttis non euisque morbipen a sdapibulum orna.</p>
            <p>Urnau ltrices quis curabitur pha sellent esque congue magnisve stib ulum quismodo nulla et.</p>
            <p class="readmore"><a href="#">Continue Reading &raquo;</a></p>
          </li>
        </ul>
        <br class="clear" />
      </div>
    </div>
    <div class="column">
      <div class="holder"><a href="#"><img src="media/300x250.gif" alt="" /></a></div>
      <div class="holder"><a href="#"><img src="media/300x80.gif" alt="" /></a></div>
    </div>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->

{% endblock %}